spring:
  application:
    name: api-gateway-application
  cloud:
    config:
      enabled: false

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8083/eureka}
