apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dep
  labels:
    app: gateway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
        - image: javasre2022/gateway
          imagePullPolicy: Always
          name: gateway-api
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-api
  ports:
    - port: 8082
      targetPort: 8082
