---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-deployment
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
      - image: keoffor/gateway:latest
        env:
          - name: VALIDATION
            value: http://$(USER_SERVICE_SERVICE_HOST):8081/users/validate
          - name: EUREKA_URI
            value: http://(EUREKA_SERVICE_SERVICE_HOST):8083/eureka
          - name: ANGULAR_URI
            value: http://104.154.243.74:80
        imagePullPolicy: Always
        name: gatewaycontainer
        ports:
        - containerPort: 8084


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service
  name: gatewayservice
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http-gateway
      port: 8084
      targetPort: 8084
  selector:
    app: gateway-deployment








